import { useMemo, useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/Button.tsx'
import { Input, Select, Textarea } from '@/components/ui/Input.tsx'
import { Modal } from '@/components/ui/Modal.tsx'
import { Badge } from '@/components/ui/Badge.tsx'
import { formatINR, formatDate, PAYOUT_STATUS_COLORS } from '@/lib/utils'
import { Banknote, Coins, Wallet, ChevronRight, Search, Filter, ExternalLink, TrendingUp, AlertCircle, RefreshCw } from 'lucide-react'
import toast from 'react-hot-toast'

/**
 * Admin Payouts dashboard.
 * Combines two data sources to give a single broker-centric view:
 *   - payout_distributions: per-payment MLM commission as customer pays (the earnings ledger)
 *   - bp_payout_transactions: explicit broker payout requests, usually generated by cycle close (the actual payout queue)
 *
 * Per-broker, we show: total earned, total in pending payout batches, total paid out, balance owed.
 * Expand to see line items.
 */
export default function Payouts() {
  const qc = useQueryClient()
  const [statusF, setStatusF] = useState('')
  const [search, setSearch] = useState('')
  const [expanded, setExpanded] = useState<Set<string>>(new Set())

  // ── Queries ──────────────────────────────────────────────────────
  const { data: distributions = [], isLoading: distLoading } = useQuery({
    queryKey: ['payout_distributions_all'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('payout_distributions')
        .select('id, beneficiary_broker_id, booking_id, level, income_type, gross_payout, tds_amount, admin_charge, net_payout, created_at, status, bp_bookings(booking_no)')
        .order('created_at', { ascending: false })
        .limit(2000)
      if (error) throw error
      return data || []
    },
  })

  const { data: txns = [], isLoading: txnLoading } = useQuery({
    queryKey: ['bp_payout_transactions_all', statusF],
    queryFn: async () => {
      let q = supabase.from('bp_payout_transactions')
        .select('*, brokers(name, broker_id, pan_no, tds_applicable), bp_bookings(booking_no)')
        .order('created_at', { ascending: false })
      if (statusF) q = q.eq('status', statusF)
      const { data, error } = await q
      if (error) throw error
      return data || []
    },
  })

  const { data: brokers = [] } = useQuery({
    queryKey: ['brokers_lite_payouts'],
    queryFn: async () => {
      const { data } = await supabase.from('brokers').select('id, name, broker_id, rank, kyc_status, pan_no, tds_applicable').order('name')
      return data || []
    },
  })

  const update = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: any }) => {
      const { error } = await supabase.from('bp_payout_transactions').update({ ...data, updated_at: new Date().toISOString() }).eq('id', id)
      if (error) throw error
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['bp_payout_transactions_all'] })
      qc.invalidateQueries({ queryKey: ['payout_distributions_all'] })
      qc.invalidateQueries({ queryKey: ['payouts'] })
      toast.success('Payout updated')
    },
    onError: (e: any) => toast.error(e.message),
  })

  // ── Aggregate per broker ────────────────────────────────────────
  const aggregated = useMemo(() => {
    const map = new Map<string, any>()
    const brokerLookup: Record<string, any> = {}
    for (const b of (brokers as any[])) brokerLookup[b.id] = b

    // Distributions = earnings
    for (const d of (distributions as any[])) {
      const k = d.beneficiary_broker_id
      if (!k) continue
      if (!map.has(k)) {
        const b = brokerLookup[k]
        map.set(k, { broker_id: k, broker: b, earned: 0, paid: 0, pending_payout: 0, approved_payout: 0, txns: [] as any[], distributions: [] as any[] })
      }
      const row = map.get(k)
      row.earned += Number(d.net_payout || 0)
      row.distributions.push(d)
    }

    // Transactions = payout requests / batches
    for (const t of (txns as any[])) {
      const k = t.broker_id
      if (!k) continue
      if (!map.has(k)) {
        const b = brokerLookup[k]
        map.set(k, { broker_id: k, broker: b || t.brokers, earned: 0, paid: 0, pending_payout: 0, approved_payout: 0, txns: [] as any[], distributions: [] as any[] })
      }
      const row = map.get(k)
      row.txns.push(t)
      const net = Number(t.net_amount || t.amount || 0)
      if (t.status === 'paid')     row.paid += net
      else if (t.status === 'approved') row.approved_payout += net
      else if (t.status === 'pending')  row.pending_payout += net
    }

    return Array.from(map.values())
      .map(r => ({ ...r, balance: Math.max(0, r.earned - r.paid - r.approved_payout - r.pending_payout) }))
      .sort((a, b) => (b.earned + b.paid) - (a.earned + a.paid))
  }, [distributions, txns, brokers])

  // ── KPIs ────────────────────────────────────────────────────────
  const kpis = useMemo(() => {
    const totalEarned = aggregated.reduce((s, r) => s + r.earned, 0)
    const totalPaid   = aggregated.reduce((s, r) => s + r.paid, 0)
    const totalPending = aggregated.reduce((s, r) => s + r.pending_payout, 0)
    const totalApproved = aggregated.reduce((s, r) => s + r.approved_payout, 0)
    return { totalEarned, totalPaid, totalPending, totalApproved, brokerCount: aggregated.length }
  }, [aggregated])

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase()
    if (!q) return aggregated
    return aggregated.filter(r =>
      (r.broker?.name || '').toLowerCase().includes(q) ||
      (r.broker?.broker_id || '').toLowerCase().includes(q)
    )
  }, [aggregated, search])

  // ── Manage transaction modal ────────────────────────────────────
  const [selected, setSelected] = useState<any>(null)
  const [modal, setModal] = useState(false)
  const [form, setForm] = useState<any>({ status:'', payment_mode:'', utr_ref:'', paid_date:'', rejection_reason:'', notes:'', tds_amount:'', net_amount:'' })
  const openTxn = (r: any) => {
    setSelected(r)
    setForm({
      status: r.status, payment_mode: r.payment_mode || '', utr_ref: r.utr_ref || '',
      paid_date: r.paid_date || '', rejection_reason: r.rejection_reason || '', notes: r.notes || '',
      tds_amount: r.tds_amount || '', net_amount: r.net_amount || ''
    })
    setModal(true)
  }
  const save = async () => {
    await update.mutateAsync({
      id: selected.id,
      data: { ...form, tds_amount: form.tds_amount ? Number(form.tds_amount) : null, net_amount: form.net_amount ? Number(form.net_amount) : null }
    })
    setModal(false)
  }
  const set = (k: string, v: any) => setForm((p: any) => ({ ...p, [k]: v }))

  const toggleExpand = (id: string) => setExpanded(prev => { const n = new Set(prev); n.has(id) ? n.delete(id) : n.add(id); return n })

  return (
    <div className="p-3 md:p-6 space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-emerald-50 rounded-lg"><Banknote size={20} className="text-emerald-600"/></div>
          <div>
            <h1 className="text-xl font-bold text-gray-900">Broker Payouts</h1>
            <p className="text-sm text-gray-500">Earned · Approved · Paid · Owed — per broker. Click any broker to see their commission history and active payout requests.</p>
          </div>
        </div>
        <span className="text-[11px] text-gray-400 inline-flex items-center gap-1" title="Commissions auto-recompute whenever a payment changes">
          <RefreshCw size={12}/>Auto-synced on every payment
        </span>
      </div>

      {/* KPIs */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
        <Kpi icon={<Coins size={16}/>}      label="Total earned"   value={formatINR(kpis.totalEarned)}   sub={`${kpis.brokerCount} brokers`} tint="bg-emerald-50 border-emerald-200 text-emerald-700"/>
        <Kpi icon={<Wallet size={16}/>}     label="Paid out"        value={formatINR(kpis.totalPaid)}     sub="lifetime"                      tint="bg-blue-50 border-blue-200 text-blue-700"/>
        <Kpi icon={<TrendingUp size={16}/>} label="Approved (queued)" value={formatINR(kpis.totalApproved)} sub="ready to pay"                tint="bg-amber-50 border-amber-200 text-amber-700"/>
        <Kpi icon={<Filter size={16}/>}     label="Pending review"  value={formatINR(kpis.totalPending)}  sub="awaiting approval"             tint="bg-orange-50 border-orange-200 text-orange-700"/>
        <Kpi icon={<AlertCircle size={16}/>}label="Owed to brokers" value={formatINR(filtered.reduce((s, r) => s + r.balance, 0))} sub="earned − paid − queued" tint="bg-rose-50 border-rose-200 text-rose-700"/>
      </div>

      {/* Filters */}
      <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-3 flex flex-wrap gap-2 items-center">
        <div className="relative flex-1 min-w-[200px]">
          <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/>
          <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search broker name or code..."
            className="w-full pl-8 pr-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-300"/>
        </div>
        <select value={statusF} onChange={e => setStatusF(e.target.value)} className="border border-gray-200 rounded-lg px-2 py-2 text-sm focus:outline-none">
          {['','pending','approved','paid','rejected','hold'].map(s => <option key={s} value={s}>{s ? `Txn status: ${s}` : 'All txn statuses'}</option>)}
        </select>
        <div className="text-xs text-gray-500 ml-auto">{filtered.length} brokers</div>
      </div>

      {/* Broker-grouped list */}
      <div className="bg-white rounded-xl border border-gray-100 shadow-sm divide-y divide-gray-100">
        {(distLoading || txnLoading) && <div className="py-10 text-center text-sm text-gray-400">Loading…</div>}
        {!distLoading && !txnLoading && filtered.length === 0 && (
          <div className="py-10 text-center text-sm text-gray-400">No broker payouts to show.</div>
        )}
        {filtered.map(r => {
          const open = expanded.has(r.broker_id)
          const b = r.broker
          return (
            <div key={r.broker_id}>
              <button onClick={() => toggleExpand(r.broker_id)} className="w-full text-left px-4 py-3 flex items-center gap-3 hover:bg-gray-50">
                <ChevronRight size={14} className={`text-gray-400 shrink-0 transition-transform ${open ? 'rotate-90' : ''}`}/>
                <div className="flex-1 min-w-0">
                  <div className="font-semibold text-gray-900 truncate">{b?.name || '—'}</div>
                  <div className="text-xs text-gray-500 truncate">
                    <span className="font-mono">[{b?.broker_id || r.broker_id.slice(0,8)}]</span>
                    {b?.rank && <span> · {b.rank}</span>}
                    {b?.kyc_status && b.kyc_status !== 'approved' && <span className="ml-2 text-amber-700">KYC {b.kyc_status}</span>}
                  </div>
                </div>
                <div className="text-right shrink-0 hidden sm:block">
                  <div className="text-[10px] text-gray-400">Earned</div>
                  <div className="font-bold text-emerald-700">{formatINR(r.earned)}</div>
                </div>
                <div className="text-right shrink-0 hidden sm:block">
                  <div className="text-[10px] text-gray-400">Paid</div>
                  <div className="font-bold text-blue-700">{formatINR(r.paid)}</div>
                </div>
                <div className="text-right shrink-0">
                  <div className="text-[10px] text-gray-400">Owed</div>
                  <div className={`font-bold ${r.balance > 0 ? 'text-rose-700' : 'text-gray-400'}`}>{formatINR(r.balance)}</div>
                </div>
                <Link to={`/broker/dashboard?broker_id=${r.broker_id}`}
                  onClick={e => e.stopPropagation()}
                  className="ml-2 inline-flex items-center gap-1 text-xs px-2 py-1 rounded-md border border-gray-200 hover:bg-gray-50">
                  <ExternalLink size={11}/>Portal
                </Link>
              </button>

              {open && (
                <div className="bg-gray-50/60 px-12 py-4 border-t border-gray-100 space-y-4">
                  {/* Pending txns */}
                  <div>
                    <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Payout transactions ({r.txns.length})</div>
                    {r.txns.length === 0 ? (
                      <div className="rounded-lg border border-dashed border-gray-300 bg-white py-4 text-center text-xs text-gray-400">No payout transactions yet. Close a Payout Cycle to generate one.</div>
                    ) : (
                      <div className="bg-white rounded-lg border border-gray-200 overflow-x-auto">
                        <table className="w-full text-xs">
                          <thead className="bg-gray-50 text-gray-500">
                            <tr>{['Created','Type','Booking','Gross','TDS','Net','Status','UTR','Paid Date','Action'].map(h => <th key={h} className="px-3 py-2 text-left">{h}</th>)}</tr>
                          </thead>
                          <tbody className="divide-y divide-gray-50">
                            {r.txns.map((t: any) => (
                              <tr key={t.id}>
                                <td className="px-3 py-2 whitespace-nowrap">{formatDate(t.created_at)}</td>
                                <td className="px-3 py-2 capitalize">{t.payout_type || '—'}</td>
                                <td className="px-3 py-2 font-mono text-blue-700">{t.bp_bookings?.booking_no || '—'}</td>
                                <td className="px-3 py-2">{formatINR(t.amount)}</td>
                                <td className="px-3 py-2 text-rose-600">−{formatINR(t.tds_amount || 0)}</td>
                                <td className="px-3 py-2 font-semibold text-emerald-700">{formatINR(t.net_amount || 0)}</td>
                                <td className="px-3 py-2"><Badge label={t.status} className={PAYOUT_STATUS_COLORS[t.status] || 'bg-gray-100 text-gray-700'}/></td>
                                <td className="px-3 py-2 font-mono">{t.utr_ref || '—'}</td>
                                <td className="px-3 py-2">{t.paid_date ? formatDate(t.paid_date) : '—'}</td>
                                <td className="px-3 py-2">
                                  <Button size="sm" variant="ghost" onClick={() => openTxn(t)}>Manage</Button>
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}
                  </div>

                  {/* Distributions = per-payment earnings ledger */}
                  <div>
                    <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Earnings ledger ({r.distributions.length} entries · {formatINR(r.earned)} net)</div>
                    {r.distributions.length === 0 ? (
                      <div className="rounded-lg border border-dashed border-gray-300 bg-white py-4 text-center text-xs text-gray-400">No commissions earned yet. MLM distributions appear here as customers pay.</div>
                    ) : (
                      <div className="bg-white rounded-lg border border-gray-200 overflow-x-auto max-h-80 overflow-y-auto">
                        <table className="w-full text-xs">
                          <thead className="bg-gray-50 text-gray-500 sticky top-0">
                            <tr>{['Date','Booking','Type','Level','Gross','TDS','Admin','Net'].map(h => <th key={h} className="px-3 py-2 text-left">{h}</th>)}</tr>
                          </thead>
                          <tbody className="divide-y divide-gray-50">
                            {r.distributions.slice(0, 100).map((d: any) => (
                              <tr key={d.id}>
                                <td className="px-3 py-1.5 whitespace-nowrap">{formatDate(d.created_at)}</td>
                                <td className="px-3 py-1.5 font-mono text-blue-700">{d.bp_bookings?.booking_no || '—'}</td>
                                <td className="px-3 py-1.5 capitalize">{d.income_type}</td>
                                <td className="px-3 py-1.5">{d.level === 0 ? 'Self' : `L${d.level}`}</td>
                                <td className="px-3 py-1.5">{formatINR(d.gross_payout)}</td>
                                <td className="px-3 py-1.5 text-rose-600">−{formatINR(d.tds_amount || 0)}</td>
                                <td className="px-3 py-1.5 text-amber-700">−{formatINR(d.admin_charge || 0)}</td>
                                <td className="px-3 py-1.5 font-semibold text-emerald-700">{formatINR(d.net_payout)}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                        {r.distributions.length > 100 && (
                          <div className="px-3 py-2 text-[10px] text-gray-400 bg-gray-50">… and {r.distributions.length - 100} more</div>
                        )}
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          )
        })}
      </div>

      {/* Manage transaction modal */}
      <Modal open={modal} onClose={() => setModal(false)} title="Manage Payout Transaction">
        {selected && (
          <div className="space-y-4">
            <div className="bg-blue-50 rounded-lg p-4 text-sm grid grid-cols-2 gap-2">
              <div><span className="text-gray-500">Broker:</span> <strong>{selected.brokers?.name}</strong></div>
              <div><span className="text-gray-500">Gross:</span> <strong>{formatINR(selected.amount)}</strong></div>
              <div><span className="text-gray-500">PAN:</span> {selected.brokers?.pan_no || '—'}</div>
              <div><span className="text-gray-500">TDS applicable:</span> {selected.brokers?.tds_applicable ? 'Yes' : 'No'}</div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <Select label="Status" value={form.status} onChange={(e: any) => set('status', e.target.value)}>
                {['pending','approved','paid','rejected','hold'].map(s => <option key={s} value={s}>{s}</option>)}
              </Select>
              <Select label="Payment Mode" value={form.payment_mode} onChange={(e: any) => set('payment_mode', e.target.value)}>
                <option value="">Select</option>
                {['neft','rtgs','imps','upi','cheque'].map(m => <option key={m} value={m}>{m.toUpperCase()}</option>)}
              </Select>
              <Input label="UTR / Ref No" value={form.utr_ref} onChange={(e: any) => set('utr_ref', e.target.value)} />
              <Input label="Paid Date" type="date" value={form.paid_date} onChange={(e: any) => set('paid_date', e.target.value)} />
              <Input label="TDS Amount (₹)" type="number" value={form.tds_amount} onChange={(e: any) => set('tds_amount', e.target.value)} />
              <Input label="Net Amount (₹)" type="number" value={form.net_amount} onChange={(e: any) => set('net_amount', e.target.value)} />
              <Textarea label="Notes" value={form.notes} onChange={(e: any) => set('notes', e.target.value)} className="col-span-2" rows={2} />
            </div>
          </div>
        )}
        <div className="flex justify-end gap-2 mt-6">
          <Button variant="secondary" onClick={() => setModal(false)}>Cancel</Button>
          <Button onClick={save} loading={update.isPending}>Update</Button>
        </div>
      </Modal>
    </div>
  )
}

function Kpi({ icon, label, value, sub, tint }: any) {
  return (
    <div className={`rounded-xl border p-3 ${tint}`}>
      <div className="flex items-center justify-between mb-0.5">
        {icon}<div className="text-base md:text-lg font-bold">{value}</div>
      </div>
      <div className="text-xs text-gray-500">{label}</div>
      {sub && <div className="text-[10px] text-gray-400">{sub}</div>}
    </div>
  )
}
