-- =============================================================
-- Migration: EMI Plans, EMI Schedule, E-Pin System
-- Date: 2026-04-30
-- Repo: fanbe-payout-admin
-- =============================================================

-- ─────────────────────────────────────────────────────────────
-- 1. EMI PLANS
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bp_emi_plans (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id         UUID NOT NULL REFERENCES bp_bookings(id) ON DELETE CASCADE,
  frequency          TEXT NOT NULL CHECK (frequency IN ('monthly','quarterly','half_yearly','annually')),
  installment_count  INTEGER NOT NULL CHECK (installment_count > 0),
  installment_amount NUMERIC(14,2) NOT NULL,
  interest_rate      NUMERIC(5,2)  NOT NULL DEFAULT 0,  -- % per installment
  start_date         DATE NOT NULL,
  late_fee_per_day   NUMERIC(10,2) NOT NULL DEFAULT 0,
  bounce_charge      NUMERIC(10,2) NOT NULL DEFAULT 500,
  total_amount       NUMERIC(14,2) GENERATED ALWAYS AS (installment_count * installment_amount) STORED,
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE bp_emi_plans IS 'One EMI plan per booking. Defines the instalment schedule parameters.';

-- ─────────────────────────────────────────────────────────────
-- 2. EMI SCHEDULE (auto-generated rows per plan)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bp_emi_schedule (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id                UUID NOT NULL REFERENCES bp_emi_plans(id) ON DELETE CASCADE,
  booking_id             UUID NOT NULL REFERENCES bp_bookings(id) ON DELETE CASCADE,
  installment_no         INTEGER NOT NULL,
  due_date               DATE NOT NULL,
  principal_amount       NUMERIC(14,2) NOT NULL,
  interest_amount        NUMERIC(10,2) NOT NULL DEFAULT 0,
  total_due              NUMERIC(14,2) NOT NULL,
  late_fee_per_day       NUMERIC(10,2) NOT NULL DEFAULT 0,
  bounce_charge          NUMERIC(10,2) NOT NULL DEFAULT 0,
  status                 TEXT NOT NULL DEFAULT 'pending'
                           CHECK (status IN ('pending','paid','overdue','waived','bounced')),
  paid_date              DATE,
  payment_reference      TEXT,
  days_late              INTEGER DEFAULT 0,
  late_fee_charged       NUMERIC(10,2) DEFAULT 0,
  bounce_charge_applied  NUMERIC(10,2) DEFAULT 0,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (plan_id, installment_no)
);

COMMENT ON TABLE bp_emi_schedule IS 'Individual instalment rows generated from bp_emi_plans.';

-- Auto-set status = overdue for unpaid instalments past due_date
CREATE OR REPLACE FUNCTION fn_emi_auto_overdue()
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  UPDATE bp_emi_schedule
     SET status = 'overdue', updated_at = now()
   WHERE status = 'pending'
     AND due_date < CURRENT_DATE;
END;
$$;

COMMENT ON FUNCTION fn_emi_auto_overdue IS 'Call daily via pg_cron or Supabase cron to mark overdue instalments.';

-- Trigger: keep updated_at fresh
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_emi_plans_updated_at'
  ) THEN
    CREATE TRIGGER trg_emi_plans_updated_at
      BEFORE UPDATE ON bp_emi_plans
      FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_emi_schedule_updated_at'
  ) THEN
    CREATE TRIGGER trg_emi_schedule_updated_at
      BEFORE UPDATE ON bp_emi_schedule
      FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────
-- 3. E-PIN / REGISTRATION CODES
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bp_epins (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code         TEXT NOT NULL UNIQUE,          -- 8-char alphanumeric, generated by app
  status       TEXT NOT NULL DEFAULT 'unused'
                 CHECK (status IN ('unused','used','expired','revoked')),
  expiry_date  DATE,                          -- NULL = no expiry
  used_by      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  used_at      TIMESTAMPTZ,
  notes        TEXT,                          -- e.g. batch name / camp
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE bp_epins IS 'Admin-generated one-time registration codes for broker/agent self-signup.';

CREATE INDEX IF NOT EXISTS idx_epins_code   ON bp_epins (code);
CREATE INDEX IF NOT EXISTS idx_epins_status ON bp_epins (status);

-- Auto-expire codes past their expiry_date
CREATE OR REPLACE FUNCTION fn_epin_auto_expire()
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  UPDATE bp_epins
     SET status = 'expired', updated_at = now()
   WHERE status = 'unused'
     AND expiry_date IS NOT NULL
     AND expiry_date < CURRENT_DATE;
END;
$$;

COMMENT ON FUNCTION fn_epin_auto_expire IS 'Call daily to expire unused codes past their expiry_date.';

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_epins_updated_at'
  ) THEN
    CREATE TRIGGER trg_epins_updated_at
      BEFORE UPDATE ON bp_epins
      FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────
-- 4. ROW LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────

-- EMI Plans
ALTER TABLE bp_emi_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admin_all_emi_plans"
  ON bp_emi_plans FOR ALL
  USING (auth.role() = 'authenticated');

-- EMI Schedule
ALTER TABLE bp_emi_schedule ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admin_all_emi_schedule"
  ON bp_emi_schedule FOR ALL
  USING (auth.role() = 'authenticated');

-- E-Pins
ALTER TABLE bp_epins ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admin_all_epins"
  ON bp_epins FOR ALL
  USING (auth.role() = 'authenticated');

-- ─────────────────────────────────────────────────────────────
-- 5. INDEXES
-- ─────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_emi_plans_booking    ON bp_emi_plans    (booking_id);
CREATE INDEX IF NOT EXISTS idx_emi_schedule_plan    ON bp_emi_schedule (plan_id);
CREATE INDEX IF NOT EXISTS idx_emi_schedule_booking ON bp_emi_schedule (booking_id);
CREATE INDEX IF NOT EXISTS idx_emi_schedule_status  ON bp_emi_schedule (status);
CREATE INDEX IF NOT EXISTS idx_emi_schedule_due     ON bp_emi_schedule (due_date);
